### ISSUE TITLE
Anyone still interested in this work?

### ISSUE THREAD

**Issue by wcravens** [ykaw/PiCW#1]
Hello,

I've been playing with this codebase for a couple of days.  I've been interested in using a RPi for a key for a while.  I got around to it and ran into your codebase.  I figured I'd just try and see if there was anyone else still interested.

Wes

**Comment by ykaw** [comment]
So far you are the only person who has contacted me interested in this program.
It is also available on YouTube, but has gotten very few comments.
https://youtu.be/2BrhcRPj1FE
https://youtu.be/GpT2TFPGSUM

Thank you for your interest.

**Comment by wcravens** [comment]
Cool, thanks.  I'm exploring designs because I want to work on an interactive training keyer.  Similar to some that already exist but preferably with more network abilities.

I managed to get PiCW up and running pretty easily.  And it got me introduced to pigpio, so thank you!!!
