### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by jacksnodgrass** [ykaw/PiCW#2]
I've running rasbian ( bullseye ) on a Raspberry Pi 4. 

I cloned the .git code. 

If I try and run it I get: 
./PiCW.py 
Traceback (most recent call last):
  File "/home/jack/PiCW/./PiCW.py", line 9, in <module>
    import InputOutputPort as port
ModuleNotFoundError: No module named 'InputOutputPort'

what am I missing / doing wrong? 

- jack

**Comment by ykaw** [comment]
When using PiCW, install the GPIO driver pigpio or RPi_GPIO and create InputOutputPort.py as a symbolic link to the corresponding module.

`ln -s InputOutputPort_pigpio.py InputOutputPort.py`
or
`ln -s InputOutputPort_RPi_GPIO.py InputOutputPort.py`

Both can be used, but pigpio has better performance and is recommended.

for your info, these are the demo videos:
https://youtu.be/2BrhcRPj1FE
https://youtu.be/GpT2TFPGSUM

TNX FR using PiCW. 73 from ex JH0NUQ

**Comment by jacksnodgrass** [comment]
is: 
ln -s InputOutputPort_pigpio.py InputOutputPort.py
or
ln -s InputOutputPort_RPi_GPIO.py InputOutputPort.py
documented someplace in github and I didn't see it?  Seems like that should be in the README.md file. 

it works once I did: ln -s InputOutputPort_pigpio.py InputOutputPort.py

- jack

**Comment by ykaw** [comment]
Sorry, I did not describe it in the README. We will update it soon.
